Repository apache/flink-connector-elasticsearch, pull requests merged in 2025-04, with the labels that each got.

#122 [FLINK-37636] Fix compile error in weekly CI.
  .github/workflows/weekly.yml
Labels: component=BuildSystem

#123 [FLINK-37675] Update `elastic.yml` for 3.1.0 release
  docs/data/elastic.yml
Labels: component=Documentation

#124 [FLINK-37694] Update version to 4.1-SNAPSHOT
  flink-connector-elasticsearch-base/pom.xml
  flink-connector-elasticsearch-e2e-tests/flink-connector-elasticsearch-e2e-tests-common/pom.xml
  flink-connector-elasticsearch-e2e-tests/flink-connector-elasticsearch6-e2e-tests/pom.xml
  flink-connector-elasticsearch-e2e-tests/flink-connector-elasticsearch7-e2e-tests/pom.xml
  flink-connector-elasticsearch-e2e-tests/pom.xml
  flink-connector-elasticsearch6/pom.xml
  flink-connector-elasticsearch7/pom.xml
  flink-connector-elasticsearch8/pom.xml
  flink-sql-connector-elasticsearch6/pom.xml
  flink-sql-connector-elasticsearch7/pom.xml
  pom.xml
Labels: component=Connectors/Elasticsearch
